language: node_js
node_js:
  - "6"

env:
  global:
    - REACT_APP_DEV_URL=krasnov-burberry-fake-shop-for-study-dev
    - REACT_APP_PROD_URL=krasnov-burberry-fake-shop-for-study

cache: 
  yarn: true
  directories: 
    -node_modules

before_script:
  - npm run fix

script:
  - npm run lint

after_success:
  - npm run build

deploy:
  - provider: script
    skip_cleanup: true
    script: now alias $NOW_URL $REACT_APP_PROD_URL
    on:
      branch: master

  - provider: script
    skip_cleanup: true
    script: now alias $NOW_URL $REACT_APP_DEV_URL
    on:
      branch: develop
