language: node_js
node_js:
  - "6"

cache: 
  yarn: true
  directories: 
    -node_modules
    
script:
  - npm run lint

after_success:
  - npm run build

deploy:
  - provider: script
    email: fl.krasnov@gmail.com
    skip_cleanup: true
    script: now alias deploymentId $REACT_APP_PROD_URL
    on:
      branch: master

  - provider: script
    email: fl.krasnov@gmail.com
    skip_cleanup: true
    script: now alias deploymentId $REACT_APP_DEV_URL
    on:
      branch: develop