language: node_js
node_js:
  - "6"

cache: 
  yarn: true
  directories: 
    -node_modules
    
script:
  - npm run lint

after_success:
  - npm run build

deploy:
  - provider: script
    skip_cleanup: true
    script: now alias -t $NOW_TOKEN $(now build --public -t $NOW_TOKEN) $REACT_APP_PROD_URL
    on:
      branch: master

  - provider: script
    skip_cleanup: true
    script: now alias -t $NOW_TOKEN $(now build --public -t $NOW_TOKEN) $REACT_APP_DEV_URL
    on:
      branch: dev